#!/usr/bin/env python3
"""
Test script for validating the pairs_to_fragment_counts.py functionality.

This test:
1. Runs the pairs_to_fragment_counts.py script on the input file "test_data/mesc_microc_test.pairs"
2. Executes the complete pipeline (convert→sort→count→index→cleanup) with scale factors
3. Generates a tabix-indexed counts file with embedded normalization scale factors
4. Calculates the MD5 checksum of the output file and compares it with a hardcoded expected value
5. Includes appropriate error handling and clear success/failure messages
6. Cleans up any temporary files created during testing

The test validates the complete pipeline functionality including:
- Pairs to fragments conversion
- Fragment sorting and counting
- Normalization scale factor computation
- Tabix indexing with scale factor headers
- Proper file format and compression
"""

import sys
import subprocess
import tempfile
import hashlib
import gzip
import shutil
import unittest
import warnings
from pathlib import Path


class TestPairsToFragmentCounts(unittest.TestCase):
    """Test case for validating the pairs_to_fragment_counts.py functionality."""

    @classmethod
    def setUpClass(cls):
        """Set up test environment."""
        # Find the repository root directory
        cls.repo_root = Path(__file__).parent.parent.absolute()

        # Define paths
        cls.pairs_to_fragment_counts_script = cls.repo_root / "code" / "pairs_to_fragment_counts.py"
        cls.input_pairs_file = cls.repo_root / "test_data" / "mesc_microc_test.pairs"

        # Create a temporary directory for test outputs
        cls.temp_dir = tempfile.mkdtemp()
        cls.temp_output_file = Path(cls.temp_dir) / "test_output.counts.tsv.gz"

        # Hardcoded expected MD5 checksum of the current correct output
        # This was generated by running the current script and calculating the MD5
        # Note: This matches the existing reference file test_data/mesc_microc_test.counts.tsv.gz
        cls.expected_md5 = "48e6474267eefc6a27578ae23e762f55"

        # Check if required files exist
        if not cls.pairs_to_fragment_counts_script.exists():
            raise FileNotFoundError(f"Script not found: {cls.pairs_to_fragment_counts_script}")
        if not cls.input_pairs_file.exists():
            raise FileNotFoundError(f"Input pairs file not found: {cls.input_pairs_file}")

    @classmethod
    def tearDownClass(cls):
        """Clean up after tests."""
        # Remove temporary directory and its contents
        shutil.rmtree(cls.temp_dir)

    def calculate_md5(self, file_path):
        """Calculate MD5 checksum of a file."""
        md5_hash = hashlib.md5()

        # Handle gzipped files
        if str(file_path).endswith('.gz'):
            with gzip.open(file_path, 'rb') as f:
                for chunk in iter(lambda: f.read(4096), b""):
                    md5_hash.update(chunk)
        else:
            with open(file_path, 'rb') as f:
                for chunk in iter(lambda: f.read(4096), b""):
                    md5_hash.update(chunk)

        return md5_hash.hexdigest()

    def check_command_exists(self, command):
        """Check if a command exists in the system PATH."""
        try:
            subprocess.run(["which", command], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
            return True
        except subprocess.CalledProcessError:
            return False

    def test_pairs_to_fragment_counts_pipeline(self):
        """Test the complete pairs_to_fragment_counts pipeline."""
        
        try:
            # Run pairs_to_fragment_counts.py
            cmd = [
                sys.executable,
                str(self.pairs_to_fragment_counts_script),
                str(self.input_pairs_file),
                "-o", str(self.temp_output_file)
            ]
            
            print(f"Running: {' '.join(cmd)}")
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            
            if result.returncode != 0:
                self.fail(f"pairs_to_fragment_counts.py failed with return code {result.returncode}\n"
                         f"STDOUT: {result.stdout}\n"
                         f"STDERR: {result.stderr}")
            
            # Check if output file was created
            self.assertTrue(self.temp_output_file.exists(), 
                          f"Output file was not created: {self.temp_output_file}")
            
            # Check if tabix index was created
            index_file = Path(str(self.temp_output_file) + ".tbi")
            self.assertTrue(index_file.exists(), 
                          f"Tabix index file was not created: {index_file}")
            
            # Verify the file is properly gzipped
            self.assertTrue(str(self.temp_output_file).endswith('.gz'), 
                          "Output file should be gzip compressed")
            
            # Verify we can read the gzipped file
            try:
                with gzip.open(self.temp_output_file, 'rt') as f:
                    first_line = f.readline()
                    # Should start with scale factors header
                    self.assertTrue(first_line.startswith('# scale_factors:'), 
                                  f"First line should be scale factors header, got: {first_line[:50]}...")
            except Exception as e:
                self.fail(f"Could not read gzipped output file: {e}")
            
            # Calculate MD5 checksum of the generated file
            generated_md5 = self.calculate_md5(self.temp_output_file)
            
            # Print checksums for debugging
            print(f"Expected MD5: {self.expected_md5}")
            print(f"Generated MD5: {generated_md5}")
            
            # Verify file structure by examining content
            with gzip.open(self.temp_output_file, 'rt') as f:
                lines = f.readlines()
                
                print(f"Output file has {len(lines)} lines")
                
                # Check first few lines
                if len(lines) >= 3:
                    print("First 3 lines:")
                    for i in range(3):
                        print(f"  Line {i+1}: {lines[i].strip()}")
                
                # Verify structure
                self.assertTrue(len(lines) > 2, "File should have header + data lines")
                self.assertTrue(lines[0].startswith('# scale_factors:'), 
                              "First line should be scale factors header")
                self.assertTrue(lines[1].startswith('#chrom\t'), 
                              "Second line should be column header")
                
                # Check data lines format
                if len(lines) > 2:
                    data_line = lines[2].strip().split('\t')
                    self.assertEqual(len(data_line), 4, 
                                   f"Data lines should have 4 columns, got {len(data_line)}")
            
            # Compare generated MD5 with expected MD5
            self.assertEqual(self.expected_md5, generated_md5,
                           f"Generated counts file does not match the expected output.\n"
                           f"Expected MD5: {self.expected_md5}\n"
                           f"Generated MD5: {generated_md5}\n"
                           f"This could indicate a change in the pairs_to_fragment_counts.py script "
                           f"or its dependencies. If the change is intentional, please update the "
                           f"expected MD5 in the test.")

            print("✅ Test passed: Generated counts file matches the expected output")
            print(f"✅ Pipeline successfully created tabix-indexed file with scale factors")

        except subprocess.CalledProcessError as e:
            self.fail(f"Pipeline execution failed: {e}")
        except subprocess.TimeoutExpired:
            self.fail("Pipeline execution timed out after 5 minutes")
        except Exception as e:
            self.fail(f"Test failed with error: {e}")

    def test_pairs_to_fragment_counts_help(self):
        """Test that the help message works correctly."""
        cmd = [sys.executable, str(self.pairs_to_fragment_counts_script), "--help"]
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            
            # Help should exit with code 0 and contain expected text
            self.assertEqual(result.returncode, 0, "Help command should exit with code 0")
            self.assertIn("Fragment Pairs to Fragment Counts Pipeline", result.stdout,
                         "Help output should contain script description")
            self.assertIn("pairs_to_fragments_tsv.py", result.stdout,
                         "Help should mention the underlying conversion script")
            
            print("✅ Help message test passed")
            
        except subprocess.TimeoutExpired:
            self.fail("Help command timed out")
        except Exception as e:
            self.fail(f"Help test failed: {e}")


if __name__ == "__main__":
    unittest.main()
